### ISSUE TITLE
[BUG] Error in temporal_qc

### ISSUE THREAD

**Issue by oesteban** [preprocessed-connectomes-project/quality-assessment-protocol#11]
Invalid cast:

```
Traceback (most recent call last):
  File "anaconda/lib/python2.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 18, in run_node
    result['result'] = node.run(updatehash=updatehash)
  File "anaconda/lib/python2.7/site-packages/nipype/pipeline/engine.py", line 1428, in run
    self._run_interface()
  File "anaconda/lib/python2.7/site-packages/nipype/pipeline/engine.py", line 1538, in _run_interface
    self._result = self._run_command(execute)
  File "anaconda/lib/python2.7/site-packages/nipype/pipeline/engine.py", line 1664, in _run_command
    result = self._interface.run()
  File "anaconda/lib/python2.7/site-packages/nipype/interfaces/base.py", line 1033, in run
    runtime = self._run_wrapper(runtime)
  File "anaconda/lib/python2.7/site-packages/nipype/interfaces/base.py", line 983, in _run_wrapper
    runtime = self._run_interface(runtime)
  File "anaconda/lib/python2.7/site-packages/nipype/interfaces/utility.py", line 445, in _run_interface
    out = function_handle(**args)
  File "<string>", line 21, in qap_functional_temporal
  File "quality-assessment-protocol/qap/temporal_qc.py", line 176, in mean_outlier_timepoints
    outliers        = outlier_timepoints(*args, **kwrds)
  File "quality-assessment-protocol/qap/temporal_qc.py", line 169, in outlier_timepoints
    outliers= [ float(l.strip()) for l in lines ] # note: don't really need strip
ValueError: could not convert string to float: *+ WARNING:   If you are performing spatial transformations on an oblique dset,
```

**Comment by chrisgorgo** [comment]
I believe I fixed that. Are you using current master?

**Comment by oesteban** [comment]
Ok, there were some updates in master. I'll double check now.

EDIT: I close the issue. If not fixed, I will reopen it.
